CREATE TABLE `puzzles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`source_name` text NOT NULL,
	`game_title` text NOT NULL,
	`white` text NOT NULL,
	`black` text NOT NULL,
	`event` text NOT NULL,
	`played_at` text NOT NULL,
	`move_number` integer NOT NULL,
	`ply` integer NOT NULL,
	`side` text NOT NULL,
	`fen_before` text NOT NULL,
	`fen_after` text NOT NULL,
	`played_move_san` text NOT NULL,
	`played_move_uci` text NOT NULL,
	`best_move_san` text NOT NULL,
	`best_move_uci` text NOT NULL,
	`loss_cp` integer NOT NULL,
	`severity` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`solves` integer DEFAULT 0 NOT NULL,
	`last_practiced_at` text
);
