ALTER TABLE puzzles ADD COLUMN analysis_depth INTEGER NOT NULL DEFAULT 18;
ALTER TABLE games ADD COLUMN analysis_depth INTEGER NOT NULL DEFAULT 18;
ALTER TABLE user_settings ADD COLUMN analysis_depth INTEGER NOT NULL DEFAULT 18;
